#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "FATAL: Run as root."
  exit 1
fi

apt update && apt install clang gcc clangd gdb cmake make ninja nvim ruby gem htop tig tmux pip fish lolcat cowsay fortunes fortune-mod

gem install --user-install solargraph
pip install cmake-language-server

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim --headless +PlugInstall +qall

#TODO
# fish (+ plugins) starship fd rg bat autojump(fasd) fzf

# alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
# dotfiles checkout
