#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "FATAL: Run as root."
  exit 1
fi

apt update && apt install clang gcc clangd nvim

# ruby solargraph

#TODO
# fish (+ plugins) starship fd bat autojump fzf

# nvim install plugins command

# install nerdfont?
# kitty config?

# alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
# dotfiles checkout
