#!/bin/bash

# TODO: fix sudo flags to create directories of correct ownership

if [[ $(id -u) -ne 0 ]]; then
  echo "FATAL: Run as root."
  exit 1
fi

add-apt-repository ppa:aacebedo/fasd ppa:neovim-ppa/unstable
apt update
apt install clang gcc clangd gdb cmake make ninja-build neovim ruby ruby-dev gem htop tig tmux pip fish lolcat cowsay fortunes fortune-mod ripgrep fd-find fasd tldr pry
apt install -o Dpkg::Options::="--force-overwrite" bat

gem install --user-install solargraph
pip install cmake-language-server

git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
$HOME/.fzf/install

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim --headless +PackerInstall +'TSInstall cpp ruby python java lua vim cmake bash' +qall

sh -c "$(curl -fsSL https://starship.rs/install.sh)"

chsh -s /usr/bin/fish

fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
fish -c 'fisher install fishgretel/fasd'
